In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel('Выборка_Казань.xlsx', sheet_name = 0)

In [3]:
df.columns

Index(['ID', 'Мусор', 'dup', 'outlier', 'out_PCA', 'Цена', 'Цена_перв',
       'LN(Цена)', 'BC(Цена)', 'Цена_перв.1', 'Цена(кв.м)', 'Цена(кв.м)_ln',
       'Прогноз', 'кв.м', 'MAE', 'MAPE', 'out', 'Исп', 'Комм', 'ОПлощадь',
       'Этаж_1', 'Этаж_2', 'Этаж_3', 'Этаж_4', 'Этажность_1', 'ГП_1', 'ГП_2',
       'Неточности', 'ГП', 'Unnamed: 29', 'Unnamed: 30', 'Разница', 'Испол',
       'Ремонт_1', 'Ремонт_2', 'Раст_центр_1', 'Раст_центр_2', 'Раст_метро_1',
       'Раст_метро_2', 'Районы_1', 'Районы_2', 'Районы_3', 'Районы_4',
       'Районы_5', 'Районы_6', 'Medians', 'ЖК_БД', 'ЖК_БД_ч',
       'Многоуровневость', 'Терраса', 'Вид_1', 'Вид_2', 'DB', 'KM',
       'Аварийноть', 'Проверка', 'Инфо', 'Адрес_1', 'Адрес_2', 'Адрес_Ya',
       'Долгота', 'Широта', 'Сцепка_к', 'Unnamed: 63', 'ПОИСК', 'Текст',
       'Ремонт', 'Общая площадь', 'Год постройки', 'Этаж/Этажность', 'Ссылка'],
      dtype='object')

<font size = 3><div style="text-align: justify">**Проверка DF на тип данных и пропуски:**</div></font>

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11942 entries, 0 to 11941
Data columns (total 71 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   id                11942 non-null  object 
 1   мусор             11942 non-null  int64  
 2   dup               11942 non-null  int64  
 3   outlier           11942 non-null  int64  
 4   out_pca           10119 non-null  float64
 5   цена              11942 non-null  int64  
 6   цена_перв         11934 non-null  object 
 7   ln(цена)          11942 non-null  float64
 8   bc(цена)          11934 non-null  float64
 9   цена_перв.1       1807 non-null   float64
 10  цена(кв.м)        11942 non-null  float64
 11  цена(кв.м)_ln     11938 non-null  float64
 12  прогноз           9499 non-null   float64
 13  кв.м              10065 non-null  float64
 14  mae               10065 non-null  float64
 15  mape              10065 non-null  float64
 16  out               278 non-null    float6

In [4]:
df.dtypes

ID                 object
Мусор               int64
dup                 int64
outlier             int64
out_PCA           float64
                   ...   
Ремонт             object
Общая площадь      object
Год постройки      object
Этаж/Этажность     object
Ссылка             object
Length: 71, dtype: object

In [8]:
df.isnull().sum()

id                   0
мусор                0
dup                  0
outlier              0
out_pca           1823
                  ... 
ремонт              10
общая_площадь     8405
год_постройки     8484
этаж/этажность    8406
ссылка               0
Length: 71, dtype: int64

<font size = 3><div style="text-align: justify">**Описательная статистика для числовых факторов:**</div></font>

In [10]:
df_num = df[['цена', 'оплощадь', 'этаж_1', 'этажность_1', 'гп_2']] #отбираем необходимые числовые факторы

df_num.describe()

цена      оплощадь        этаж_1   этажность_1          гп_2
count  1.194200e+04  11942.000000  11941.000000  11941.000000  11699.000000
mean   9.355517e+06     52.242025      5.871284     10.927393   2001.881699
std    1.256589e+07     29.685913      4.771997      6.521836     22.118679
min    6.500000e+05      9.100000      1.000000      1.000000   1898.000000
25%    5.300000e+06     35.000000      2.000000      5.000000   1983.000000
50%    7.400000e+06     45.900000      4.000000      9.000000   2010.000000
75%    1.088000e+07     62.800000      8.000000     17.000000   2020.000000
max    1.000000e+09    508.900000     33.000000     40.000000   2027.000000

<font size = 3><div style="text-align: justify">**Описательная статистика для категориальных факторов:**</div></font>

In [12]:
df_cat = df[['этаж_4', 'раст_центр_2', 'раст_метро_2', 'районы_2', 'жк_бд']] #отбираем необходимые категориальные факторы

df_cat.describe()

этаж_4      раст_центр_2 раст_метро_2          районы_2  жк_бд
count       11942             11942        11942             11734  11942
unique          7                 5            3                38      2
top     этажи_2-5  от_6000_до_10000  на_удалении  клыковка_дальний    нет
freq         4807              3766        10128              1091  11796

<font size = 3><div style="text-align: justify">**Простая фильтрация:**</div></font>

In [17]:
#По одному фильтру 
sort_1 = df[df['этаж_4'] == 'этажи_2-5']
print(len(sort_1))
print(sort_1['этаж_4'].unique())

4807
['этажи_2-5']


In [57]:
#По нескольким фильтрам
s_1 = df['этаж_4'] == 'этажи_2-5'
s_2 = df['оплощадь'] >= 30
s_3 = df['оплощадь'] <= 35
s_4 = df['районы_2'] != 'Азино'

sort_1 = df[s_1 & s_2 & s_3 & s_4]

print(f'Мин площадь: {sort_1["оплощадь"].min()}, Макс площадь: {sort_1["оплощадь"].max()}')
print(sort_1['этаж_4'].unique())

if 'Азино' == list(sort_1['районы_2'].unique()):
    print('Район есть')
else:
    print('Района нет')

Мин площадь: 30.0, Макс площадь: 35.0
['этажи_2-5']
Района нет


In [59]:
#По нескольким фильтрам
s_1 = df['сцепка_к'] == '49.206271_55.689431'
s_2 = df['сцепка_к'] == '49.216709_55.777125'
s_3 = df['сцепка_к'] == '49.207753_55.795767'

sort_1 = df[s_1 | s_2 | s_3]  # | оператор "или"
 
print(sort_1['сцепка_к'].unique())

['49.206271_55.689431' '49.207753_55.795767' '49.216709_55.777125']


<font size = 3><div style="text-align: justify">**Сортировка:**</div></font>

In [62]:
s_1 = df['оплощадь'] >= 30
s_2 = df['оплощадь'] <= 35

sort_1 = df[s_1 & s_2]['оплощадь'].sort_values(ascending = False) #ascending = False - по убыванию, True - по возрастанию.
sort_1

11941    35.0
3108     35.0
3094     35.0
7829     35.0
9827     35.0
         ... 
3573     30.0
3088     30.0
9142     30.0
8270     30.0
4101     30.0
Name: оплощадь, Length: 1665, dtype: float64

<font size = 3><div style="text-align: justify">**Количество по классам:**</div></font>

In [64]:
df['этаж_4'].value_counts(sort = True, ascending = False)

этажи_2-5      4807
этажи_6-10     2422
последний      1586
этажи_11-25    1507
первый         1466
неважно         146
более_25          8
Name: этаж_4, dtype: int64

<font size = 3><div style="text-align: justify">**Список уникальных классов по категориальному фактору:**</div></font>

In [67]:
list(df['этаж_4'].unique())

['первый',
 'последний',
 'этажи_2-5',
 'этажи_6-10',
 'этажи_11-25',
 'неважно',
 'более_25']

<font size = 3><div style="text-align: justify">**Перевод всех имен столбцов к нижнему регистру и замена пробелов символом подчеркивания:**</div></font>

In [4]:
df.columns = df.columns.str.lower().str.replace(' ', '_')
df.columns

Index(['id', 'мусор', 'dup', 'outlier', 'out_pca', 'цена', 'цена_перв',
       'ln(цена)', 'bc(цена)', 'цена_перв.1', 'цена(кв.м)', 'цена(кв.м)_ln',
       'прогноз', 'кв.м', 'mae', 'mape', 'out', 'исп', 'комм', 'оплощадь',
       'этаж_1', 'этаж_2', 'этаж_3', 'этаж_4', 'этажность_1', 'гп_1', 'гп_2',
       'неточности', 'гп', 'unnamed:_29', 'unnamed:_30', 'разница', 'испол',
       'ремонт_1', 'ремонт_2', 'раст_центр_1', 'раст_центр_2', 'раст_метро_1',
       'раст_метро_2', 'районы_1', 'районы_2', 'районы_3', 'районы_4',
       'районы_5', 'районы_6', 'medians', 'жк_бд', 'жк_бд_ч',
       'многоуровневость', 'терраса', 'вид_1', 'вид_2', 'db', 'km',
       'аварийноть', 'проверка', 'инфо', 'адрес_1', 'адрес_2', 'адрес_ya',
       'долгота', 'широта', 'сцепка_к', 'unnamed:_63', 'поиск', 'текст',
       'ремонт', 'общая_площадь', 'год_постройки', 'этаж/этажность', 'ссылка'],
      dtype='object')

<font size = 3><div style="text-align: justify">**Перевод всех имен классов к нижнему регистру и замена пробелов символом подчеркивания:**</div></font>

In [5]:
string_columns = list(df.dtypes[df.dtypes == 'object'].index) #выбираем индексы всех категориальных факторов (столбцов)

for col in string_columns:
    df[col] = df[col].str.lower().str.replace(' ', '_') #понижаем регистр и ставим _ вместо пробелов

<font size = 3><div style="text-align: justify">**Удаление столбцов в DF:**</div></font>

In [ ]:
# Удаляем лишние столбцы
df = df.drop(['Ссылка', 'Способ продажи'], axis = 1)
df

<font size = 3><div style="text-align: justify">**Логарифмирование:**</div></font>

In [ ]:
np.log(df['Цена'])

In [ ]:
np.log1p(df['Цена']) #добавляет 1 к значению, так как в ячейке может быть 0

<font size = 3><div style="text-align: justify">**Перемешивание**</div></font>

In [69]:
idx = np.arange(5) #массив от 0 до 4
print(idx)
np.random.shuffle(idx)
print(idx)

[0 1 2 3 4]
[4 1 2 0 3]


<font size = 3><div style="text-align: justify">**loc / iloc**</div></font>

In [72]:
#loc - по индексам
#iloc - по позициям

df.loc[0:1] #выводит строки с 0 и 1 индексом

id  мусор  dup  outlier  out_pca     цена    цена_перв   ln(цена)  \
0  1_avito      0    0        0      0.0  5200000  5_200_000_₽  15.464169   
1  2_avito      0    0        0      0.0  5390000  5_390_000_₽  15.500056   

   bc(цена)  цена_перв.1  ...     широта             сцепка_к  unnamed:_63  \
0  4.897233          NaN  ...  55.852829  49.063304_55.852829          4.0   
1  4.899012          NaN  ...  55.689431  49.206271_55.689431          3.0   

   поиск                                              текст  ремонт  \
0    0.0  продаю_1к_квартиру-студию_27_квм_в_новом_жк_но...    евро   
1    0.0  срочная_продажа_новой_квартиры-_студиипродаетс...    евро   

   общая_площадь год_постройки этаж/этажность  \
0            NaN           NaN            NaN   
1            NaN           NaN            NaN   

                                              ссылка  
0  https://www.avito.ru/kazan/kvartiry/kvartira-s...  
1  https://www.avito.ru/kazan/kvartiry/kvartira-s...  

[2 rows x 71 columns]

In [74]:
df.iloc[0:2] #выводит строки на позициях 0 и 1 не включая 2

id  мусор  dup  outlier  out_pca     цена    цена_перв   ln(цена)  \
0  1_avito      0    0        0      0.0  5200000  5_200_000_₽  15.464169   
1  2_avito      0    0        0      0.0  5390000  5_390_000_₽  15.500056   

   bc(цена)  цена_перв.1  ...     широта             сцепка_к  unnamed:_63  \
0  4.897233          NaN  ...  55.852829  49.063304_55.852829          4.0   
1  4.899012          NaN  ...  55.689431  49.206271_55.689431          3.0   

   поиск                                              текст  ремонт  \
0    0.0  продаю_1к_квартиру-студию_27_квм_в_новом_жк_но...    евро   
1    0.0  срочная_продажа_новой_квартиры-_студиипродаетс...    евро   

   общая_площадь год_постройки этаж/этажность  \
0            NaN           NaN            NaN   
1            NaN           NaN            NaN   

                                              ссылка  
0  https://www.avito.ru/kazan/kvartiry/kvartira-s...  
1  https://www.avito.ru/kazan/kvartiry/kvartira-s...  

[2 rows x 71 columns]

<font size = 3><div style="text-align: justify">**Добавить элемент к списку:**</div></font>

In [76]:
a = [1, 2, 3, 4, 5]
print(a)
a = [0] + a
print(a)

[1, 2, 3, 4, 5]
[0, 1, 2, 3, 4, 5]


<font size = 3><div style="text-align: justify">**Умножение:**</div></font>

In [77]:
a = [1, 2, 3, 4, 5]
b = 5

c = a * b
c

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [79]:
c = np.array(a).dot(b)
c

array([ 5, 10, 15, 20, 25])

<font size = 3><div style="text-align: justify">**Заполнение пропусков нулями:**</div></font>

In [ ]:
df['оплощадь'] = df['оплощадь'].fillna(0)

<font size = 3><div style="text-align: justify">**Удаление пропусков:**</div></font>

In [ ]:
df_ts = df_ts.dropna(subset = ['Тип санузла'])

<font size = 3><div style="text-align: justify">**Обнаружение пропусков:**</div></font>

In [101]:
df['оплощадь'].isna() #возвращает True, если есть пропуск

0        False
1        False
2        False
3        False
4        False
         ...  
11937    False
11938    False
11939    False
11940    False
11941    False
Name: оплощадь, Length: 11942, dtype: bool

<font size = 3><div style="text-align: justify">**Переименование столбцов:**</div></font>

In [ ]:
# переименнуе столбцы
df_ts = df_ts.rename({0: 'первый', 1: 'последний', 2: 'средний'}, axis = 'columns')
df_ts

<font size = 3><div style="text-align: justify">**Как добавить переменную в текст:**</div></font>

In [82]:
#f-строка
a = 3
b = 5
c = 3

print(f'Яблок: {a}, груш: {b}')
print('num_doors_%s' % c)

Яблок: 3, груш: 5
num_doors_3


<font size = 3><div style="text-align: justify">**Изменение типа данных:**</div></font>

In [91]:
a = [1, 2, 3, 4, 5]
type(a)

list

In [93]:
a = [1, 2, 3, 4, 5]
type(str(a))

str

In [100]:
df['оплощадь'].astype(int).head(5)

0    27
1    31
2    38
3    40
4    44
Name: оплощадь, dtype: int64

<font size = 3><div style="text-align: justify">**Изменение классов по категориальному фактору:**</div></font>

In [ ]:
df_ts = df['Тип санузла'].map({' совмещенный' : ' совмещенный', ' раздельный' : ' раздельный',
                             ' совмещенный, раздельный' : ' совмещенный'})
df['Тип санузла'] = df_ts
df

<font size = 3><div style="text-align: justify">**Перевод категориального бинарного признака в число:**</div></font>

In [7]:
(df['Вид_1'] == 'есть').astype(int).head(10)

0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    0
8    0
9    0
Name: Вид_1, dtype: int64

<font size = 3><div style="text-align: justify">**Переместить столбик на другое место в таблице:**</div></font>

In [ ]:
index = df_first.index
df_first.insert(0, 'index', index)
df_first